### ISSUE TITLE
运行test_resize时，cuda输出全是0

### ISSUE THREAD

**Issue by thunder95** [inisis/Capella#1]
OpenCv Cpu code ran in: 8.940096 msecs.
Own Cuda code ran in: 0.012352 msecs.
Difference at pos 0
Reference: 220
GPU      : 0
Difference at pos 1
Reference: 217
GPU      : 0
Difference at pos 2
Reference: 219
GPU      : 0
Difference at pos 3
Reference: 220
GPU      : 0

**Comment by inisis** [comment]
你好 你是不是用的图灵（20系例的）卡，需要修改下src/CMakeLists.txt 里面的-gencode arch=compute_61,code=sm_61

**Comment by thunder95** [comment]
> 你好 你是不是用的图灵（20系例的）卡，需要修改下src/CMakeLists.txt 里面的-gencode arch=compute_61,code=sm_61

你好， 我用的是GeForce RTX 2070 super显卡， 尝试了52,61， 62， 73， 输出都是0，没有变化

**Comment by inisis** [comment]
你可以试下这个 -gencode=arch=compute_75,code="sm_75,compute_75"

**Comment by thunder95** [comment]
大佬真厉害，设置成75果然就可以运行了。虽然新手表示不懂为啥72不行，只有后面继续再回头看看了。
